version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/api/src
      - ./nodemon.json:/api/nodemon.json
    container_name: api
    expose:
      - '3000'
    ports: 
      - '3000:3000'
    links:
      - mongodb
    command: npm run dev-with-docker

  mongodb:
    image: mongo:4.0.23-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    links:
      - mongodb:mongo

volumes:
  data: