version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/api/src
      - ./nodemon.json:/api/nodemon.json
    container_name: api_dev
    environment:
        NODE_ENV: dev
    expose:
      - '3000'
    ports: 
      - '3000:3000'
    links:
      - mongodb:mongo
    command: npm run dev-with-docker-2

  mongodb:
    image: mongo:4.0.23-xenial
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongodb:mongo

volumes:
  data: